/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import static codigo.Tokens.Coma;
import static codigo.Tokens.Igual;
import static codigo.Tokens.Punto;
import static codigo.Tokens.PuntoComa;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Charly Ponce
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalizar = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(487, 560));
        setPreferredSize(new java.awt.Dimension(500, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnalizar.setBackground(new java.awt.Color(204, 255, 255));
        btnAnalizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAnalizar.setText("Analizar");
        btnAnalizar.setBorder(null);
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 121, 40));

        btnLimpiar1.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpiar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.setBorder(null);
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 121, 40));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 372, 470, 170));

        TextArea1.setColumns(20);
        TextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextArea1.setRows(5);
        jScrollPane2.setViewportView(TextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
       // TODO add your handling code here:
File archivo = new File("archivo.txt");
PrintWriter escribir;

try {
    escribir = new PrintWriter(archivo);
    escribir.print(TextArea1.getText()); // Guarda lo escrito en el área de texto
    escribir.close();
} catch (FileNotFoundException ex) {
    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
}

try {
    Reader lector = new BufferedReader(new FileReader("archivo.txt"));
    Lexer lexer = new Lexer(lector);
    String resultado = "";

    while (true) {
        Tokens tokens = lexer.yylex();
        if (tokens == null) {
            resultado += "FIN";
            txtResultado.setText(resultado);
            return;
        }

   switch (tokens) {
    case ERROR:
        resultado += lexer.lexeme + ": ERROR Símbolo no reconocido\n";
        break;

    case Identificador:
        resultado += lexer.lexeme + ": Es un identificador\n";
        break;

    case Numero:
        resultado += lexer.lexeme + ": Es un número\n";
        break;

    case Punto:
        resultado += lexer.lexeme + ": Es un punto\n";
        break;

    case Coma:
        resultado += lexer.lexeme + ": Es una coma\n";
        break;

    case PuntoComa:
        resultado += lexer.lexeme + ": Es un punto y coma\n";
        break;

    case Igual:
        resultado += lexer.lexeme + ": Es un símbolo igual\n";
        break;

    case ParentesisA:
        resultado += lexer.lexeme + ": Es un paréntesis de apertura\n";
        break;

    case ParentesisC:
        resultado += lexer.lexeme + ": Es un paréntesis de cierre\n";
        break;

    // Palabras reservadas
    case Robot:
        resultado += lexer.lexeme + ": Es una palabra reservada\n";
        break;

    case Iniciar:
        resultado += lexer.lexeme + ": Es una palabra reservada\n";
        break;

    // Métodos
    case Velocidad:
    case Base:
    case Cuerpo:
    case Garra:
    case AbrirGarra:
    case CerrarGarra:
    case Repetir:
        resultado += lexer.lexeme + ": Es un método\n";
        break;

    default:
        resultado += lexer.lexeme + ": Token desconocido\n";
        break;
}

    }

} catch (FileNotFoundException ex) {
    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
} catch (IOException ex) {
    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
            TextArea1.setText("");

    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
